server:
  port: 8008

spring:
  application:
    name: deepexi-service-customer-feign

  http:
    encoding:
      charset: UTF-8

  devtools:
    restart:
      enabled: true #热部署生效
      additional-paths: src/main/java #设置重启的目录
      #exclude: application.yml #classpath目录下的WEB-INF文件夹内容修改不重启

eureka:      # 将服务注册到注册中心
  client:
    register-with-eureka: false
    #fetch-registry: false
    service-url:
      #defaultZone: http://localhost:8003/eureka #多个时，逗号分隔
      defaultZone: http://eureka.com:8003/eureka/,http://eureka.one.com:8006/eureka/,http://eureka.two.com:8007/eureka/
    #enabled: true

feign:
  hystrix:
    enabled: true
